[package]
name = "moyumax-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "moyumax_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
moyumax-core = { path = "../../../crates/moyumax-core" }
serde.workspace = true
tauri.workspace = true
uuid.workspace = true

[features]
default = []
