// MCMOD（mcmod.cn）收录热门模组的中文名与中文简介映射。
// 仅在简体/繁体中文界面展示;链接跳转 MCMOD 搜索页(条目 ID 无法从 slug 稳定推导,
// 不伪造深层链接)。未命中的项目显示 MCMOD 搜索入口兜底。
// 覆盖范围:主流优化/库/科技/魔法/冒险/装饰/存储/世界生成模组;
// 更全数据需接 MCMOD 数据文件(后续里程碑),本表持续补充。

export interface McmodEntry {
  /** 中文显示名。 */
  zhName: string;
  /** 一句话中文简介。 */
  zhDescription: string;
  /** MCMOD 跳转链接(搜索页)。 */
  mcmodUrl: string;
}

function entry(zhName: string, zhDescription: string, slug: string): McmodEntry {
  return {
    zhName,
    zhDescription,
    mcmodUrl: `https://search.mcmod.cn/s?key=${encodeURIComponent(slug)}`,
  };
}

/** 任意项目经 MCMOD 搜索跳转的兜底链接。 */
export function mcmodSearchUrl(term: string): string {
  return `https://search.mcmod.cn/s?key=${encodeURIComponent(term)}`;
}

export const MCMOD_ENTRIES: Record<string, McmodEntry> = {
  // ---- 优化与渲染 ----
  "sodium": entry("钠 (Sodium)", "现代化渲染引擎，大幅提升帧率并改善画面稳定性。", "Sodium"),
  "lithium": entry("锂 (Lithium)", "不改动原版行为的游戏逻辑性能优化。", "Lithium"),
  "iris": entry("Iris 光影", "现代光影加载器，兼容 OptiFine 光影包。", "Iris Shaders"),
  "sodium-extra": entry("钠扩展 (Sodium Extra)", "为钠补充设置界面与细节画质选项。", "Sodium Extra"),
  "continuity": entry("连续性 (Continuity)", "为方块纹理提供连续连接效果。", "Continuity"),
  "fabric-api": entry("Fabric API", "Fabric 加载器官方 API，绝大多数 Fabric 模组的前置。", "Fabric API"),
  "modmenu": entry("模组菜单 (Mod Menu)", "在游戏内查看和管理已安装的模组。", "Mod Menu"),
  "cloth-config": entry("Cloth Config", "常见的模组配置界面库，许多模组的前置。", "Cloth Config"),
  "architectury-api": entry("Architectury", "跨加载器模组开发 API。", "Architectury"),
  "ferrite-core": entry("FerriteCore", "降低游戏内存占用。", "FerriteCore"),
  "krypton": entry("Krypton", "网络栈与性能优化。", "Krypton"),
  "starlight": entry("星光 (Starlight)", "重写光照引擎，显著提升光照计算性能。", "Starlight"),
  "immediatelyfast": entry("ImmediatelyFast", "界面与文本渲染优化。", "ImmediatelyFast"),
  "dynamic-fps": entry("动态帧率 (Dynamic FPS)", "窗口失焦时自动降低帧率，省电降噪。", "Dynamic FPS"),
  "entityculling": entry("实体剔除 (Entity Culling)", "不渲染被遮挡的实体，减轻渲染压力。", "Entity Culling"),
  "modernfix": entry("现代修复 (ModernFix)", "综合性能与稳定性改进。", "ModernFix"),
  "lazydfu": entry("LazyDFU", "延迟数据修复初始化，加快游戏启动。", "LazyDFU"),
  "embeddium": entry("Embeddium", "Forge 端的高性能渲染优化（钠系分支）。", "Embeddium"),
  "oculus": entry("Oculus", "Forge 端的光影加载器（Iris 系分支）。", "Oculus"),
  "rubidium": entry("Rubidium", "Forge 端的渲染优化（钠系分支）。", "Rubidium"),
  "reeses-sodium-options": entry("RSO 视频设置", "钠系模组的视频设置界面。", "Reese's Sodium Options"),
  "vulkanmod": entry("VulkanMod", "用 Vulkan 重写渲染管线，提升性能。", "VulkanMod"),
  "c2me": entry("C2ME 并发引擎", "并发区块引擎，加速世界生成与加载。", "C2ME"),
  "noisium": entry("Noisium", "世界生成性能优化。", "Noisium"),
  "servercore": entry("服务器核心 (ServerCore)", "服务端性能优化与卡顿削减。", "ServerCore"),
  "alternate-current": entry("交流电 (Alternate Current)", "红石系统性能优化。", "Alternate Current"),
  "entity-model-features": entry("实体模型特性 (EMF)", "自定义实体模型支持（OptiFine 格式）。", "Entity Model Features"),
  "entity-texture-features": entry("实体纹理特性 (ETF)", "自定义实体纹理与发光层（OptiFine 格式）。", "Entity Texture Features"),
  "citresewn": entry("CIT 自定义纹理", "自定义物品纹理支持（OptiFine 格式）。", "CIT Resewn"),
  "lambdynamiclights": entry("Lamb 动态光源", "手持光源实时照明。", "LambDynamicLights"),
  "particle-rain": entry("粒子雨 (Particle Rain)", "更真实的雨、沙尘、极光粒子效果。", "Particle Rain"),
  "visuality": entry("视觉效果 (Visuality)", "环境粒子与细节视觉增强。", "Visuality"),
  "presence-footsteps": entry("存在脚步声 (Presence Footsteps)", "按材质变化的脚步声与落地音效。", "Presence Footsteps"),
  "sound-physics-remastered": entry("声音物理 (Sound Physics)", "环境混响与声音遮蔽模拟。", "Sound Physics Remastered"),
  "eating-animation": entry("吃东西动画 (Eating Animation)", "第三人称进食与饮用动画。", "Eating Animation"),
  "not-enough-animations": entry("更多动画 (Not Enough Animations)", "进食、划船、骑乘等动作动画。", "Not Enough Animations"),
  // ---- 信息与管理 ----
  "jei": entry("JEI 物品管理器", "查询物品、合成与用途（Just Enough Items）。", "JEI"),
  "roughly-enough-items": entry("REI 物品管理器", "物品与配方查询（Roughly Enough Items）。", "REI"),
  "emi": entry("EMI 物品管理", "新一代物品与配方查询界面。", "EMI"),
  "appleskin": entry("苹果皮 (AppleSkin)", "显示饥饿度、饱和度与食物数值细节。", "AppleSkin"),
  "jade": entry("玉 (Jade)", "方块与实体信息高亮显示（WAILA 系）。", "Jade"),
  "wthit": entry("WTHIT", "这是什么——方块实体信息显示。", "WTHIT"),
  "minihud": entry("MiniHUD", "可定制的屏幕信息覆盖层。", "MiniHUD"),
  "tweakeroo": entry("微调 (Tweakeroo)", "大量游戏操作微调与快捷开关。", "Tweakeroo"),
  "item-scroller": entry("物品滚轮 (Item Scroller)", "背包内快速移动物品。", "Item Scroller"),
  "malilib": entry("MaLiLib", "投影等模组共用的基础库。", "MaLiLib"),
  "spark": entry("spark", "游戏性能分析工具。", "spark"),
  "observable": entry("Observable", "方块实体性能观测工具。", "Observable"),
  "zoomify": entry("Zoomify", "可定制的快速变焦。", "Zoomify"),
  "inventory-sorter": entry("一键整理 (Inventory Sorter)", "背包与容器一键整理。", "Inventory Sorter"),
  "shulkerboxtooltip": entry("潜影盒预览 (ShulkerBoxTooltip)", "悬停即可查看潜影盒内容。", "ShulkerBoxTooltip"),
  "advancement-plaques": entry("进度牌匾 (Advancement Plaques)", "进度完成的沉浸式横幅提示。", "Advancement Plaques"),
  "skin-layers-3d": entry("3D 皮肤层 (Skin Layers 3D)", "以立体方式渲染皮肤外层。", "Skin Layers 3D"),
  "first-person-model": entry("第一人称模型 (First-person Model)", "第一人称可见自己的身体。", "First-person Model"),
  "wavey-capes": entry("披风飘动 (Wavey Capes)", "披风物理飘动效果。", "Wavey Capes"),
  // ---- 库与 API ----
  "bookshelf": entry("Bookshelf", "常用模组开发库。", "Bookshelf"),
  "collective": entry("Collective", "Serilum 系列模组共用的基础库。", "Collective"),
  "supermartijn642s-core-lib": entry("SuperMartijn642 核心库", "SuperMartijn642 系列模组的前置。", "SuperMartijn642's Core Lib"),
  "structurize": entry("结构化 (Structurize)", "结构扫描与放置库，模拟殖民地的前置。", "Structurize"),
  "domum-ornamentum": entry("DO 装饰 (Domum Ornamentum)", "材质继承的装饰方块库。", "Domum Ornamentum"),
  "geckolib": entry("GeckoLib", "骨骼动画与模型库。", "GeckoLib"),
  "curios": entry("饰品栏 (Curios)", "饰品与配饰槽位 API。", "Curios"),
  "patchouli": entry("帕秋莉手册 (Patchouli)", "游戏内文档手册库。", "Patchouli"),
  "kubejs": entry("KubeJS", "用 JavaScript 自定义游戏内容。", "KubeJS"),
  "rhino": entry("Rhino", "KubeJS 的脚本引擎前置。", "Rhino"),
  "terrablender": entry("TerraBlender", "世界生成兼容库，超多生物群系的前置。", "TerraBlender"),
  "bclib": entry("BCLib", "更好的末地/下界系列的前置库。", "BCLib"),
  "yungs-api": entry("YUNG's API", "YUNG 系列模组的前置库。", "YUNG's API"),
  // ---- 科技、存储与自动化 ----
  "create": entry("机械动力 (Create)", "传动、机械与自动化装置。", "Create"),
  "create-steam-n-rails": entry("机械动力：汽鸣铁道", "Create 的铁路与列车扩展。", "Create: Steam 'n' Rails"),
  "create-crafts-and-additions": entry("机械动力：工艺附加", "Create 的电力与工具扩展。", "Create Crafts & Additions"),
  "create-enchantment-industry": entry("机械动力：附魔工业", "Create 的附魔与经验处理扩展。", "Create Enchantment Industry"),
  "applied-energistics-2": entry("应用能源 2 (AE2)", "数字化存储与自动化网络。", "Applied Energistics 2"),
  "mekanism": entry("通用机械 (Mekanism)", "工业、能源与化工体系。", "Mekanism"),
  "mekanism-generators": entry("通用机械发电机", "Mekanism 的发电模块。", "Mekanism Generators"),
  "mekanism-tools": entry("通用机械工具", "Mekanism 的工具装甲模块。", "Mekanism Tools"),
  "immersive-engineering": entry("沉浸工程 (Immersive Engineering)", "复古工业风的多方块机械与电力。", "Immersive Engineering"),
  "refinedstorage": entry("精致存储 (Refined Storage)", "简洁的数字化存储网络。", "Refined Storage"),
  "sophisticated-storage": entry("精妙存储 (Sophisticated Storage)", "高扩展性的桶与箱存储系统。", "Sophisticated Storage"),
  "sophisticated-backpacks": entry("精妙背包 (Sophisticated Backpacks)", "可升级的模块化背包。", "Sophisticated Backpacks"),
  "sophisticated-core": entry("精妙核心 (Sophisticated Core)", "精妙系列的前置库。", "Sophisticated Core"),
  "iron-chests": entry("铁箱子 (Iron Chests)", "更大容量的金属箱子。", "Iron Chests"),
  "functional-storage": entry("功能存储 (Functional Storage)", "大容量抽屉式存储。", "Functional Storage"),
  "storage-drawers": entry("抽屉 (Storage Drawers)", "直观的抽屉式物品存储。", "Storage Drawers"),
  "trashcans": entry("垃圾桶 (Trashcans)", "物品与流体销毁装置。", "Trashcans"),
  "tinkers-construct": entry("匠魂 (Tinkers' Construct)", "自定义工具、武器与冶炼系统。", "Tinkers' Construct"),
  "powah": entry("Powah 能量", "易上手的能源生产与传输。", "Powah"),
  "flux-networks": entry("通量网络 (Flux Networks)", "无线能源传输网络。", "Flux Networks"),
  "extreme-reactors": entry("极限反应堆 (Extreme Reactors)", "大型核反应堆发电。", "Extreme Reactors"),
  "building-wands": entry("建筑魔杖 (Building Wands)", "快速放置与复制建筑结构。", "Building Wands"),
  "effortless-building": entry("轻松建筑 (Effortless Building)", "镜像、阵列等建筑辅助工具。", "Effortless Building"),
  "framedblocks": entry("框架方块 (FramedBlocks)", "可套用任意材质的框架方块。", "FramedBlocks"),
  // ---- 魔法与冒险 ----
  "botania": entry("植物魔法 (Botania)", "以花朵与魔力为核心的魔法科技模组。", "Botania"),
  "ars-nouveau": entry("新生魔艺 (Ars Nouveau)", "自定义法术与魔法生态。", "Ars Nouveau"),
  "irons-spells-n-spellbooks": entry("铁法术与法术书", "战斗法术、法杖与法术学校。", "Iron's Spells 'n Spellbooks"),
  "bloodmagic": entry("血魔法 (Blood Magic)", "以生命精华为代价的仪式魔法。", "Blood Magic"),
  "occultism": entry("神秘学 (Occultism)", "灵体召唤与维度魔法。", "Occultism"),
  "malum": entry("禁术 (Malum)", "阴郁风格的秘术与灵魂魔法。", "Malum"),
  "enigmaticlegacy": entry("神秘遗产 (Enigmatic Legacy)", "遗物、诅咒与奥秘探索。", "Enigmatic Legacy"),
  "forbidden-arcanus": entry("禁忌与奥秘 (Forbidden & Arcanus)", "禁忌魔法与古代遗物。", "Forbidden & Arcanus"),
  "mana-and-artifice": entry("魔法艺术 (Mana and Artifice)", "团队导向的法术与魔法体系。", "Mana and Artifice"),
  "twilight-forest": entry("暮色森林 (Twilight Forest)", "全新维度、地牢与 Boss 冒险内容。", "Twilight Forest"),
  "aether": entry("天境 (The Aether)", "经典的天空维度与冒险。", "The Aether"),
  "cataclysm": entry("灾变 (Cataclysm)", "高质量地牢、Boss 与装备。", "Cataclysm"),
  "mowzies-mobs": entry("Mowzie 的生物", "精心设计的强大生物与 Boss。", "Mowzie's Mobs"),
  "born-in-chaos": entry("生于混沌 (Born in Chaos)", "黑暗风格的敌对生物与事件。", "Born in Chaos"),
  "graveyard": entry("墓地 (The Graveyard)", "亡灵生物、墓穴与 Boss。", "The Graveyard"),
  "ice-and-fire": entry("冰与火之歌 (Ice and Fire)", "巨龙、海怪与神话生物。", "Ice and Fire"),
  "epic-fight": entry("史诗战斗 (Epic Fight)", "动作化的战斗系统与技能。", "Epic Fight"),
  "better-combat": entry("更好的战斗 (Better Combat)", "流畅的武器动作与连击。", "Better Combat"),
  "artifacts": entry("奇异饰品 (Artifacts)", "有趣的世界探索饰品与道具。", "Artifacts"),
  "alexs-mobs": entry("亚历克斯的生物 (Alex's Mobs)", "近百种真实与幻想生物。", "Alex's Mobs"),
  "naturalist": entry("自然主义者 (Naturalist)", "为群系增添真实感动物。", "Naturalist"),
  "deeperdarker": entry("深暗之域 (Deeper and Darker)", "扩展深暗之域与监守者相关内容。", "Deeper and Darker"),
  // ---- 世界生成与结构 ----
  "biomes-o-plenty": entry("超多生物群系 (Biomes O' Plenty)", "新增数十种生物群系。", "Biomes O' Plenty"),
  "terralith": entry("泰拉群系 (Terralith)", "纯数据驱动的地形美化与群系。", "Terralith"),
  "betterend": entry("更好的末地 (BetterEnd)", "大幅扩展末地群系与内容。", "BetterEnd"),
  "betternether": entry("更好的下界 (BetterNether)", "大幅扩展下界群系与内容。", "BetterNether"),
  "cinderscapes": entry("灰烬地貌 (Cinderscapes)", "下界灰烬主题群系。", "Cinderscapes"),
  "incendium": entry("烈焰下界 (Incendium)", "数据驱动的下界地形强化。", "Incendium"),
  "nullscape": entry("虚空之景 (Nullscape)", "末地虚空景观与地形强化。", "Nullscape"),
  "gardens-of-the-dead": entry("亡者花园 (Gardens of the Dead)", "下界亡灵主题群系。", "Gardens of the Dead"),
  "galosphere": entry("辉光球 (Galosphere)", "发光的洞穴晶体群系。", "Galosphere"),
  "yungs-better-dungeons": entry("更好的地牢 (YUNG's)", "重做的地牢结构与战利品。", "YUNG's Better Dungeons"),
  "yungs-better-mineshafts": entry("更好的废弃矿井 (YUNG's)", "重做的废弃矿井结构。", "YUNG's Better Mineshafts"),
  "yungs-better-strongholds": entry("更好的要塞 (YUNG's)", "重做的末地要塞结构。", "YUNG's Better Strongholds"),
  "yungs-better-ocean-monuments": entry("更好的海底神殿 (YUNG's)", "重做的海底神殿。", "YUNG's Better Ocean Monuments"),
  "yungs-better-desert-temples": entry("更好的沙漠神殿 (YUNG's)", "重做的沙漠神殿。", "YUNG's Better Desert Temples"),
  "yungs-better-jungle-temples": entry("更好的丛林神庙 (YUNG's)", "重做的丛林神庙。", "YUNG's Better Jungle Temples"),
  "yungs-better-witch-huts": entry("更好的女巫小屋 (YUNG's)", "重做的女巫小屋。", "YUNG's Better Witch Huts"),
  "yungs-better-nether-fortresses": entry("更好的下界要塞 (YUNG's)", "重做的下界要塞。", "YUNG's Better Nether Fortresses"),
  "yungs-better-end-island": entry("更好的末地岛 (YUNG's)", "重做的末地主岛。", "YUNG's Better End Island"),
  "stalwart-dungeons": entry("坚毅地牢 (Stalwart Dungeons)", "地狱与末地的大型地牢。", "Stalwart Dungeons"),
  "when-dungeons-arise": entry("地牢浮现 (When Dungeons Arise)", "大量手工设计的探索结构。", "When Dungeons Arise"),
  "repurposed-structures": entry("重复利用结构 (Repurposed Structures)", "原版结构的群系变体与扩展。", "Repurposed Structures"),
  "town-and-tower": entry("城镇与塔楼 (Towns and Towers)", "生成风格统一的聚落与高塔。", "Towns and Towers"),
  "structory": entry("Structory", "点缀世界的精致小结构。", "Structory"),
  "mo-structures": entry("Mo' Structures", "多样化的遗迹与建筑结构。", "Mo' Structures"),
  "better-archeology": entry("更好的考古 (Better Archeology)", "扩展考古玩法与文物。", "Better Archeology"),
  // ---- 农业、食物与生活 ----
  "farmers-delight": entry("农夫乐事 (Farmer's Delight)", "扩展农业、烹饪与食物系统。", "Farmer's Delight"),
  "nethers-delight": entry("下界乐事 (Nether's Delight)", "下界主题的食材与料理。", "Nether's Delight"),
  "ends-delight": entry("末地乐事 (End's Delight)", "末地主题的食材与料理。", "End's Delight"),
  "oceans-delight": entry("海洋乐事 (Ocean's Delight)", "海洋主题的食材与料理。", "Ocean's Delight"),
  "cultural-delights": entry("文化乐事 (Cultural Delights)", "玉米卷饼等文化美食扩展。", "Cultural Delights"),
  "croptopia": entry("作物盛景 (Croptopia)", "大量新作物、果树与料理。", "Croptopia"),
  "supplementaries": entry("锦致装饰 (Supplementaries)", "实用又美观的装饰与功能方块。", "Supplementaries"),
  "quark": entry("夸克 (Quark)", "大量小而美的特性集合。", "Quark"),
  "decorative-blocks": entry("装饰方块 (Decorative Blocks)", "梁柱、座椅等装饰方块。", "Decorative Blocks"),
  "chipped": entry("凿刻 (Chipped)", "数千种材质变体的建筑方块。", "Chipped"),
  "rechiseled": entry("重雕 (Rechiseled)", "方块纹理变体与雕刻。", "Rechiseled"),
  "twigs": entry("细枝 (Twigs)", "自然风格的建筑与装饰材料。", "Twigs"),
  "another-furniture": entry("另一个家具 (Another Furniture)", "现代风格的家具与装饰。", "Another Furniture"),
  "handcrafted": entry("手工艺品 (Handcrafted)", "精美的家具与装饰方块。", "Handcrafted"),
  "macaws-furniture": entry("Macaw 家具", "各种风格的家具。", "Macaw's Furniture"),
  "macaws-doors": entry("Macaw 门", "多种材质与样式的门。", "Macaw's Doors"),
  "macaws-windows": entry("Macaw 窗", "百叶窗与玻璃窗。", "Macaw's Windows"),
  "macaws-fences-and-walls": entry("Macaw 栅栏与墙", "多种栅栏、矮墙与大门。", "Macaw's Fences and Walls"),
  "macaws-roofs": entry("Macaw 屋顶", "各材质坡屋顶方块。", "Macaw's Roofs"),
  "macaws-bridges": entry("Macaw 桥梁", "木桥、铁桥与绳桥。", "Macaw's Bridges"),
  "macaws-lights-and-lamps": entry("Macaw 灯具", "室内外各式灯具。", "Macaw's Lights and Lamps"),
  "macaws-trapdoors": entry("Macaw 活板门", "多种材质活板门。", "Macaw's Trapdoors"),
  "macaws-paths-and-pavings": entry("Macaw 路径", "石板路与铺装路面。", "Macaw's Paths and Pavings"),
  "snow-real-magic": entry("真实雪 (Snow! Real Magic)", "雪的物理与视觉改进。", "Snow! Real Magic!"),
  "serene-seasons": entry("静谧四季 (Serene Seasons)", "季节变化影响世界与农业。", "Serene Seasons"),
  "ecologics": entry("生态学 (Ecologics)", "群系细节生态内容。", "Ecologics"),
  "environmental": entry("自然环境 (Environmental)", "自然风格的群系与生态扩展。", "Environmental"),
  "animal-feeding-trough": entry("动物食槽 (Animal Feeding Trough)", "自动喂养附近动物。", "Animal Feeding Trough"),
  "diagonal-fences": entry("对角栅栏 (Diagonal Fences)", "可对角放置的栅栏。", "Diagonal Fences"),
  // ---- 交通、服务器与玩法 ----
  "waystones": entry("传送石 (Waystones)", "传送石碑、回城卷轴与绑定道具。", "Waystones"),
  "journeymap": entry("旅行地图 (JourneyMap)", "实时地图、小地图与路径点标记。", "JourneyMap"),
  "xaeros-minimap": entry("Xaero 小地图", "实体雷达式小地图。", "Xaero's Minimap"),
  "xaeros-world-map": entry("Xaero 世界地图", "可缩放的全屏世界地图。", "Xaero's World Map"),
  "corpse": entry("遗体 (Corpse)", "死亡后留下保存物品的遗体。", "Corpse"),
  "corail-tombstone": entry("Corail 墓碑", "死亡生成墓碑，可寻回物品。", "Corail Tombstone"),
  "gravestone": entry("墓碑 (GraveStone)", "死亡生成墓碑并保留物品。", "GraveStone"),
  "minecolonies": entry("模拟殖民地 (MineColonies)", "建设并管理自己的殖民地。", "MineColonies"),
  "easy-villagers": entry("简单村民 (Easy Villagers)", "村民繁殖、交易与工作站优化。", "Easy Villagers"),
  "guard-villagers": entry("村民卫兵 (Guard Villagers)", "武装村民保卫村庄。", "Guard Villagers"),
  "villager-names": entry("村民名字 (Villager Names)", "为村民自动生成名字。", "Villager Names"),
  "chunky": entry("Chunky 区块加载", "高效的区块预生成与加载管理。", "Chunky"),
  "ftb-chunks": entry("FTB 区块", "区块声明、保护与加载。", "FTB Chunks"),
  "ftb-teams": entry("FTB 团队", "队伍与权限管理。", "FTB Teams"),
  "ftb-quests": entry("FTB 任务", "任务书与奖励系统。", "FTB Quests"),
  "ftb-library": entry("FTB 库", "FTB 系列的前置库。", "FTB Library"),
  "gamestages": entry("游戏阶段 (GameStages)", "按阶段解锁游戏内容。", "GameStages"),
  "item-stages": entry("物品阶段 (Item Stages)", "按阶段限制物品使用。", "Item Stages"),
  "mob-grinding-utils": entry("刷怪塔工具 (Mob Grinding Utils)", "刷怪塔专用设备与方块。", "Mob Grinding Utils"),
  "torchmaster": entry("火把大师 (Torchmaster)", "防刷怪火把与村庄照明。", "Torchmaster"),
  "iron-furnaces": entry("铁熔炉 (Iron Furnaces)", "更快的金属熔炉。", "Iron Furnaces"),
  "advanced-netherite": entry("高级下界合金 (Advanced Netherite)", "下界合金的进阶装备层级。", "Advanced Netherite"),
  "creeper-overhaul": entry("苦力怕改进 (Creeper Overhaul)", "群系主题的苦力怕变种。", "Creeper Overhaul"),
  "skeleton-overhaul": entry("骷髅改进 (Skeleton Overhaul)", "群系主题的骷髅变种。", "Skeleton Overhaul"),
  "illager-invasion": entry("掠夺者入侵 (Illager Invasion)", "掠夺者新单位与袭击事件。", "Illager Invasion"),
  "savage-and-ravage": entry("野蛮与蹂躏 (Savage & Ravage)", "掠夺者与村庄袭击扩展。", "Savage & Ravage"),
  "untitled-duck-mod": entry("无题鸭 (Untitled Duck Mod)", "为河流与湖泊增添鸭子。", "Untitled Duck Mod"),
  "figura": entry("Figura", "Lua 驱动的自定义玩家模型与动画。", "Figura"),
  "emotecraft": entry("表情工艺 (Emotecraft)", "玩家表情动作系统。", "Emotecraft"),
  "do-a-barrel-roll": entry("翻滚 (Do a Barrel Roll)", "双翅飞行的翻滚特技。", "Do a Barrel Roll"),
};

/** 按 Modrinth slug 查 MCMOD 中文条目;未收录返回 null。 */
export function mcmodEntryFor(slug: string): McmodEntry | null {
  return MCMOD_ENTRIES[slug] ?? null;
}
